### PR TITLE
Server connect

### PR DESCRIPTION
**Pull request by steveoh**
lets use this as a spot to conversate and watch commits come in.

### CODE REVIEW

**Comment by steveoh** [comment]
I'm not doing something right. My secrets must be bad.
image

**Comment by stdavis** [comment]
Host should be something like "localhost" or an ip address. Is that your problem?

-Scott

**Comment by steveoh** [comment]
that is what I am using. Weird.

**Comment by stdavis** [comment]
That is strange because I did verify that it created a good connection file on my server. 

-Scott

**Comment by steveoh** [comment]
10.2 or 10.3?

**Comment by stdavis** [comment]
10.2

On Wed, Mar 4, 2015 at 9:03 AM, steveoh notifications@github.com wrote:

> 10.2 or 10.3?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/grunt-arcgis-press/pull/11#issuecomment-77185844
> .

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC

**Pull request closed without merging**
