### PR TITLE
Use administrative api

### PR DESCRIPTION
**Pull request by steveoh**
we don't need to accept this pr. we can rebase it and clean it al up nice but I wanted it to be clear to see where I was going with changes. Thoughts @stdavis

### CODE REVIEW

**Comment by stdavis** [comment]
Not sure how this will work for multiple services. Are you thinking that each service would be a different grunt task target?

**Comment by steveoh** [comment]
good point. I'm not sure the best way that would look. I don't really like each target being a task but that could work. You would have to have different tasks for dev vs prod which could get very verbose. 

What I do like is how the options are the json schema for publishing the service opening up access for configuring everything.

**Comment by stdavis** [comment]
Agreed. One target per task would be a pain. Would be nice to be able to
specify options at the task level as well as the service level.

On Thu, Feb 26, 2015 at 8:48 AM, steveoh notifications@github.com wrote:

> good point. I'm not sure the best way that would look. I don't really like
> each target being a task but that could work. You would have to have
> different tasks for dev vs prod which could get very verbose.
> 
> What I do like is how the options are the json schema for publishing the
> service opening up access for configuring everything.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/grunt-arcgis-press/pull/7#issuecomment-76201512.

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC

**Comment by steveoh** [comment]
Try to make some time soon to play with this. Branch from here maybe?

**Comment by stdavis** [comment]
I will. Just need to finish pushing deq to production servers. Just about
there. Can you try publishing that download tool?

On Thu, Feb 26, 2015 at 8:55 AM, steveoh notifications@github.com wrote:

> Try to make some time soon to play with this. Branch from here maybe?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/grunt-arcgis-press/pull/7#issuecomment-76202995.

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC

**Comment by stdavis** [comment]
So I have depressing news. I can't find a way to make the create service (rest admin api) actually publish a map service successfully. The problem is that the [example that we have been referencing](http://server.arcgis.com/en/server/latest/administer/linux/example-publish-a-service-with-detailed-parameters.htm) is written using tools that were deprecated at 10.2! I sent them feedback about it.

We may end up having to edit sddrafts xml in a similar fashion to what you were doing before this PR.

**Pull request closed without merging**
